//      *********    DO NOT MODIFY THIS FILE     *********
//      This file is regenerated by a design tool. Making
//      changes to this file can cause errors.
namespace Expression.Blend.SampleData.SampleCommands
{
	using System; 
	using System.ComponentModel;

// To significantly reduce the sample data footprint in your production application, you can set
// the DISABLE_SAMPLE_DATA conditional compilation constant and disable sample data at runtime.
#if DISABLE_SAMPLE_DATA
	internal class SampleCommands { }
#else

	public class SampleCommands : INotifyPropertyChanged
	{
		public event PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}

		public SampleCommands()
		{
			try
			{
				Uri resourceUri = new Uri("/SuperbEdit;component/SampleData/SampleCommands/SampleCommands.xaml", UriKind.RelativeOrAbsolute);
				System.Windows.Application.LoadComponent(this, resourceUri);
			}
			catch
			{
			}
		}

		private ItemCollection _Collection = new ItemCollection();

		public ItemCollection Collection
		{
			get
			{
				return this._Collection;
			}
		}
	}

	public class Item : INotifyPropertyChanged
	{
		public event PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}

		private string _CommandName = string.Empty;

		public string CommandName
		{
			get
			{
				return this._CommandName;
			}

			set
			{
				if (this._CommandName != value)
				{
					this._CommandName = value;
					this.OnPropertyChanged("CommandName");
				}
			}
		}

		private string _CommandDescription = string.Empty;

		public string CommandDescription
		{
			get
			{
				return this._CommandDescription;
			}

			set
			{
				if (this._CommandDescription != value)
				{
					this._CommandDescription = value;
					this.OnPropertyChanged("CommandDescription");
				}
			}
		}
	}

	public class ItemCollection : System.Collections.ObjectModel.ObservableCollection<Item>
	{ 
	}
#endif
}
